<!-- resources/views/laporan_keuangan/create.blade.php -->

<h2>Tambah Laporan Keuangan</h2>

<form action="{{ route('laporan_keuangan.store') }}" method="POST">
    @csrf

    <input type="text" name="tipe" placeholder="Tipe Laporan"><br><br>

    <input type="number" name="periode_bulan" placeholder="Periode Bulan"><br><br>

    <input type="number" name="periode_tahun" placeholder="Periode Tahun"><br><br>

    <textarea name="data" placeholder="Data Laporan"></textarea><br><br>

    <input type="datetime-local" name="generated_at"><br><br>

    <input type="number" name="generated_by" placeholder="Generated By"><br><br>

    <button type="submit">Simpan</button>
</form>