<!-- resources/views/laporan_keuangan/show.blade.php -->

<h2>Detail Laporan Keuangan</h2>

<p>Tipe : {{ $laporan_keuangan->tipe }}</p>

<p>Periode Bulan : {{ $laporan_keuangan->periode_bulan }}</p>

<p>Periode Tahun : {{ $laporan_keuangan->periode_tahun }}</p>

<p>Data : {{ $laporan_keuangan->data }}</p>

<p>Generated At : {{ $laporan_keuangan->generated_at }}</p>

<p>Generated By : {{ $laporan_keuangan->generated_by }}</p>